<a href="https://colab.research.google.com/github/guilhermef2k/Sistemas_Inteligentes/blob/main/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1º Projeto - Sistemas inteligentes
Autores: <br>
Alex Bruno Duarte <br>
Guilherme de França Vasconcelos

## Introdução
---

Uma usina termoelétrica de ciclo combinado (UTCC) é uma instalação de alta eficiência que combina turbinas a gás e a vapor para gerar eletricidade. Ela reaproveita o calor dos gases de exaustão da turbina a gás (ciclo Brayton) para produzir vapor em uma caldeira, acionando uma segunda turbina (ciclo Rankine) e aumentando significativamente o rendimento. A principal vantagem é a eficiência energética, que pode chegar a 60%, reduzindo as emissões de gases de efeito estufa. <br>
Embora apresente alta eficiência, o principal desafio técnico no uso de uma usina UTCC reside na integração, sincronização e operação conjunta de dois ciclos termodinâmicos distintos (ciclo Brayton e ciclo Rankine) para funcionar de forma eficiente. Assim sendo, a potência elétrica de saída (PE) é altamente sensível às condições ambientais.

## Objetivo
---

 Construir um modelo matemático de regressão linear múltipla para prever a producão de energia baseando-se em sensores ambientais, permitindo a otimizacão do despacho energético.

## Conjunto de dados
---

Para realizar o treinamento do nosso modelo, utilizamos o dataset UCI CCPP (disponível em https://www.kaggle.com/datasets/rinichristy/combined-cycle-power-plant-data-set-uci-data). O dataset contém 9.568 amostras coletadas ao longo de 6 anos. Cada amostra possui as seguintes variáveis:


*   AT (*Ambient Temperature*): Temperatura em °C. Afeta a densidade do ar e a eficiência da combustão.*
*   V (*Exhaust Vacuum*): Vácuo de escape em cm Hg. Relacionado à pressão na turbina a vapor.
*   AP (*Ambient Pressure*): Pressão atmosférica em mbar.
*   RH (*Relative Humidity*): Umidade relativa em percentagem.
*   PE (*Net Hourly Electrical Energy Output*): A variável alvo em MW (MegaWatts).

## Modelo matemático

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import numpy as np

In [ ]:
df = pd.read_csv('/content/sample_data/Power Plant Data.csv')
df

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

### 1. Correlação entre as variáveis independentes (AT, V, AP, RH) e a variável dependente (PE)

In [ ]:
df.corr()["PE"].drop("PE")

AT   -0.948128
V    -0.869780
AP    0.518429
RH    0.389794
Name: PE, dtype: float64

É possível observar que as variáveis AT e V possuem correlação muito forte com a variável PE, portanto tem maior influência na produção de energia. Já as variáveis AP e RH possuem correlação moderada.

### 2. Correlação entre as próprias variáveis independentes (AT, V, AP, RH)

In [ ]:
var = ['AT', 'V', 'AP', 'RH']
corr = df[var].corr()
corr

          AT         V        AP        RH
AT  1.000000  0.844107 -0.507549 -0.542535
V   0.844107  1.000000 -0.413502 -0.312187
AP -0.507549 -0.413502  1.000000  0.099574
RH -0.542535 -0.312187  0.099574  1.000000

A tabela mostra forte correlação entre a variável V e AT, portanto há multicolineariedade entre elas.

### 3. Modelo de regressão linear múltipla

In [ ]:
X = df.drop(columns=["PE"])
y = df["PE"]

É possível notar que esxiste uma diferença considerável de ordem de grandeza entre as variáveis. Por isso foi adotada a normalização dos dados.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler  = MinMaxScaler(feature_range=(0, 1))
scaled  = scaler.fit_transform(X)
df_scaled = pd.DataFrame(scaled, columns=X.columns)
df_scaled

            AT         V        AP        RH
0     0.372521  0.291815  0.771591  0.638204
1     0.662040  0.669039  0.671863  0.449330
2     0.093484  0.249822  0.476862  0.892493
3     0.539660  0.568683  0.429349  0.684718
4     0.255241  0.216014  0.404355  0.952547
...        ...       ...       ...       ...
9563  0.420397  0.432918  0.522643  0.877212
9564  0.322380  0.245907  0.761693  0.552547
9565  0.835977  0.871352  0.495669  0.146381
9566  0.642210  0.784520  0.518931  0.493700
9567  0.560623  0.661210  0.602326  0.567158

[9568 rows x 4 columns]

Os dados foram divididos em conjuntos de treinamento e teste. O primeiro conjunto representa 80% dos dados e o segundo 20%.

In [ ]:
X = df_scaled
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42
)

print(f"Tamanho do dataset = {X.shape[0]} amostras")
print(f"Quantidade de amostras de treinamento = {X_train.shape[0]} amostras")
print(f"Quantidade de amostras de teste = {X_test.shape[0]} amostras")

Tamanho do dataset = 9568 amostras
Quantidade de amostras de treinamento = 7654 amostras
Quantidade de amostras de teste = 1914 amostras